import javax.swing.JFrame;
import javax.swing.JLabel;
import java.awt.Container;
import java.awt.GridLayout;

// Program to greet my family members.
public class HelloFamily extends JFrame
{
	public HelloFamily(int rows, int columns)
	{
		setTitle("Hello family!");
		Container content = getContentPane();
		content.setLayout(new GridLayout(rows, columns, 10, 20));
		content.add(new JLabel("Hello Adam!"));
		content.add(new JLabel("Hello Adrian!"));
		content.add(new JLabel("Hello Dorota!"));
		content.add(new JLabel("Hello Grzegorz!"));
		content.add(new JLabel("Hello Jola!"));
		content.add(new JLabel("Hello Lucyna!"));
		content.add(new JLabel("Hello Marek!"));
		content.add(new JLabel("Hello Milena!"));
		content.add(new JLabel("Hello Paulina!"));
		content.add(new JLabel("Hello Paweł!"));
		content.add(new JLabel("Hello Regina!"));
		content.add(new JLabel("Hello Tomek!"));

		setDefaultCloseOperation(EXIT_ON_CLOSE);
		pack();

	} // HelloFamily

	// Generated HelloFamily class and make it appear on screen.
	// Program gets two arguments defining grid - number of rows and number of columns.
	// Only non-negative integers are accepted, at least one argument must be greater than 0.
	// When both values are greater than 0, number of columns will be autogenerated.
	public static void main(String [] args)
	{
		HelloFamily theHelloFamily = new HelloFamily(Integer.parseInt(args[0]), Integer.parseInt(args[1]));
		theHelloFamily.setVisible(true);
	} // main

} // class HelloFamily