@startuml
abstract class Person
{
    - final String personName;
    - String latestSaying;
    + Person(String requiredPersonName)
    + String getPersonName()
    + String getLatestSaying()
    + abstract String getPersonType();
    + boolean isHappy()
    + abstract String getCurrentSaying();
    + speak()
    + String toString()
}

class AudienceMember extends Person
{
    + AudienceMember(String name)
    + String getPersonType()
    + String getCurrentSaying()
}

class Punter extends Person
{
    + Punter(String name)
    + String getPersonType()
    + boolean isHappy()
    + String getCurrentSaying()
}

class TVHost extends Person
{
    + TVHost(String name)
    + String getPersonType()
    + String getCurrentSaying()
}

class Director extends Person
{
    + Director(String name)
    + String getPersonType()
    + String getCurrentSaying()
}

class Psychic extends Person
{
    + Psychic(String name)
    + String getPersonType()
    + String getCurrentSaying()
}

@enduml